[package]
name = "test"
version = "0.1.0"
authors = ["xhsiung <xhsiung@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "^1.0.59"
serde_derive = "^1.0.59"
js-sys = "0.3.33"

[dependencies.wasm-bindgen]
version="^0.2"
features = ["serde-serialize"]
