[package]
name = "testmain"
version = "0.1.0"
authors = ["xhsiung <xhsiung@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.9.2"
